/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Retrieve the dashboard overview, including:
         *     - current_year: current academic year
         *     - available_years: academic years present on non-deleted projects (always includes current_year), ascending
         *     - Total project count for the selected year
         *     - Total carbon emissions grouped by organization, sorted by total carbon emission in descending order (If totals are equal, sort by organization name in ascending order)
         *     - Carbon emission per-person (scope 1–3)
         *     - Activity heatmap data
         *
         *     Query param year selects the academic year for totals/heatmap. Defaults to current_year when omitted or 0.
         */
        get: operations["get-dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owners/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get owner
         * @description Retrieve the owner details for the current user, based on the Authorization header.
         */
        get: operations["get-owners-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owners/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate owner
         * @description Verifies the owner's identity using the claims in the provided Authorization token.
         *
         *     Returns `204 No Content` if valid, or `401 Unauthorized` otherwise.
         */
        post: operations["post-owners-validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Retrieve a list of projects in the current academic year.
         *     Authenticated users can access:
         *     - Their own projects (any status).
         *     - Other users' projects that are not in draft status.
         *
         *     Projects from a previous academic year are not returned.
         *
         *     Supports sorting, filtering, searching, and pagination:
         *     - 'sort' query param: field to sort by. Prefix with '-' for descending order.
         *     - 'filter' query param: comma-separated list of statuses to filter.
         *     - 'search' query param: searches 'title' and 'custom_id', matching if input is contained in either field.
         *     - Pagination params: 'limit' and 'offset'.
         */
        get: operations["get-projects"];
        put?: never;
        /**
         * Create project
         * @description Create a new project. Only 'draft' or 'pending' status is allowed on creation.
         */
        post: operations["post-projects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/:id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project
         * @description Retrieve a specific project in the current academic year.
         *     Authenticated users can access their own projects (any status), or other users' projects that are not in draft status.
         *     Projects from a previous academic year are not accessible.
         */
        get: operations["get-projects-id"];
        put?: never;
        post?: never;
        /**
         * Delete project
         * @description Delete a project.
         *     - Users can delete owned project.
         *     - Admins can delete everyone's project.
         *     - Projects from a previous academic year are not accessible.
         */
        delete: operations["delete-projects-id"];
        options?: never;
        head?: never;
        /**
         * Update project
         * @description Update an existing project. Only the project owner is allowed.
         *
         *     Projects from a previous academic year are not accessible.
         *
         *     **Allowed statuses**
         *     - draft
         *     - fixing
         */
        patch: operations["patch-projects-id"];
        trace?: never;
    };
    "/projects/:id/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get carbon emission
         * @description Get carbon emission of a project in the current academic year.
         *     Authenticated users can view emission for their own projects (any status), or other users' projects that are not in draft status.
         *     Projects from a previous academic year are not accessible.
         */
        get: operations["get-projects-id-calculate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/:id/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate Certificate
         * @description Retrieves a PDF certificate containing details of the project's carbon usage.
         *     Authenticated users can access their own projects (any status), or other users' projects that are not in draft status.
         *     Projects from a previous academic year are not accessible.
         */
        get: operations["list-projects-id-certificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/:id/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Review project
         * @description Allows an admin to review a project.
         *
         *     Projects from a previous academic year are not accessible.
         *
         *     - If all review fields pass, the project status is set to **approved**.
         *     - If any field fails, the project status is set to **rejected**.
         *     **Allowed status transitions**
         *     - pending -> approved
         *     - pending -> rejected
         *     - rejected -> rejected
         *
         *     This endpoint will create a new review if one does not exist, or update the existing review (upsert behavior).
         */
        put: operations["put-projects-id-review"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/:id/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update project status
         * @description Update the status of a project.
         *
         *     Projects from a previous academic year are not accessible.
         *
         *     **Allowed status transitions for owner**
         *     - draft -> pending
         *     - rejected -> fixing
         *     - fixing -> pending
         *
         *     **Allowed status transitions for admin**
         *     - approved -> pending
         */
        put: operations["put-projects-id-status"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/:id/transportations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Transportation File
         * @description Download transportation file in CSV format. Only admin or owned project is allowed. Projects from a previous academic year are not accessible.
         */
        get: operations["list-projects-id-transportations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/emissionfactors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get carbon emission factor
         * @description For realtime carbon calculation
         */
        get: operations["get-projects-emissionfactors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test page */
        get: operations["list-test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activity: {
            name: string;
            unit: string;
            /** Format: double */
            value: number;
        };
        Attendee: {
            /** Format: date-time */
            date: string;
            /** Format: int64 */
            value: number;
        };
        Building: {
            /** Format: date-time */
            end_time?: string;
            facilities: string[] | null;
            /** Format: double */
            meter_value?: number;
            name: string;
            room: string;
            /** Format: date-time */
            start_time?: string;
        };
        CarbonDetailGenericScope3WithTransportations: {
            scope1: components["schemas"]["Scope1"];
            scope2: components["schemas"]["Scope2"];
            scope3: components["schemas"]["Scope3WithTransportations"];
        };
        CarbonEmissionByOrganizationItem: {
            organization: string;
            /** Format: double */
            percent: number;
            /** Format: double */
            total: number;
        };
        CarbonEmissionPerPerson: {
            /** Format: double */
            scope1: number;
            /** Format: double */
            scope2: number;
            /** Format: double */
            scope3: number;
            /** Format: double */
            total: number;
        };
        CarbonResult: {
            scope1: components["schemas"]["Scope1Result"];
            scope2: components["schemas"]["Scope2Result"];
            scope3: components["schemas"]["Scope3Result"];
        };
        CreateProjectResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateProjectResponseBody.json
             */
            readonly $schema?: string;
            project_id: string;
        };
        Dashboard: {
            available_years: number[] | null;
            carbon_emission_by_organization: components["schemas"]["CarbonEmissionByOrganizationItem"][] | null;
            carbon_emission_per_person: components["schemas"]["CarbonEmissionPerPerson"];
            /** Format: int64 */
            current_year: number;
            heatmap: components["schemas"]["Heatmap"];
            /** Format: int64 */
            total_project: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Generator: {
            /** Format: date-time */
            date: string;
            facilities: string[] | null;
            unit: string;
            /** Format: double */
            value: number;
        };
        GetCarbonEmissionResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetCarbonEmissionResponseBody.json
             */
            readonly $schema?: string;
            /** Format: double */
            carbon_emission: number;
            project_id: string;
        };
        GetDashboardResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetDashboardResponseBody.json
             */
            readonly $schema?: string;
            dashboard: components["schemas"]["Dashboard"];
        };
        GetEmissionFactorResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetEmissionFactorResponseBody.json
             */
            readonly $schema?: string;
            factors: {
                [key: string]: number;
            };
        };
        GetOwnerResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetOwnerResponseBody.json
             */
            readonly $schema?: string;
            owner: components["schemas"]["Owner"];
        };
        GetProjectResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetProjectResponseBody.json
             */
            readonly $schema?: string;
            project: components["schemas"]["ProjectDetail"];
            review?: components["schemas"]["Review"];
        };
        Heatmap: {
            electricity_usages: components["schemas"]["HeatmapItem"][] | null;
            /** Format: int64 */
            year: number;
        };
        HeatmapItem: {
            /** Format: double */
            amount: number;
            date: string;
            /** Format: int64 */
            rank: number;
        };
        ListProjectsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListProjectsResponseBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description total projects visible after filters and permissions
             */
            count: number;
            projects: components["schemas"]["ProjectListItem"][] | null;
        };
        Origin: {
            district: string;
            province: string;
        };
        Overnight: {
            /** Format: date-time */
            date: string;
            /** Format: int64 */
            value: number;
        };
        Owner: {
            email: string;
            fullname: string;
            id?: string;
            is_admin: boolean;
            line_id: string;
            major: string;
            nickname: string;
            phone_number: string;
            student_id: string;
        };
        ProjectDetail: {
            carbon_detail: components["schemas"]["CarbonDetailGenericScope3WithTransportations"];
            carbon_result: components["schemas"]["CarbonResult"];
            /** Format: date-time */
            created_at: string;
            custom_id: string;
            /** Format: date-time */
            deleted_at: string | null;
            id?: string;
            org: string;
            org_detail: string;
            owner: components["schemas"]["Owner"];
            owner_id: string;
            status: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
            updated_by: string;
            updated_owner_id: string;
        };
        ProjectListItem: {
            carbon_result: components["schemas"]["CarbonResult"];
            /** Format: date-time */
            created_at: string;
            custom_id: string;
            /** Format: date-time */
            deleted_at: string | null;
            id?: string;
            org: string;
            org_detail: string;
            owner: components["schemas"]["Owner"];
            owner_id: string;
            status: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
            updated_by: string;
            updated_owner_id: string;
        };
        Review: {
            detail: components["schemas"]["ReviewDetail"];
            id?: string;
            note: string;
            project_id: string;
        };
        ReviewCheck: {
            passed: boolean;
            rejection_notes?: string[] | null;
        };
        ReviewDetail: {
            owner: components["schemas"]["ReviewCheck"];
            project: components["schemas"]["ReviewCheck"];
            scope1: components["schemas"]["ReviewCheck"];
            scope2: components["schemas"]["ReviewCheck"];
            scope3: components["schemas"]["Scope3Review"];
        };
        ReviewUpsertInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReviewUpsertInput.json
             */
            readonly $schema?: string;
            detail: components["schemas"]["ReviewDetail"];
            note: string;
        };
        Scope1: {
            activities: components["schemas"]["Activity"][] | null;
        };
        Scope1Result: {
            /** Format: double */
            activity: number;
        };
        Scope2: {
            buildings: components["schemas"]["Building"][] | null;
            generators: components["schemas"]["Generator"][] | null;
        };
        Scope2Result: {
            /** Format: double */
            building: number;
            /** Format: double */
            generator: number;
        };
        Scope3Result: {
            /** Format: double */
            attendee: number;
            /** Format: double */
            overnight: number;
            /** Format: double */
            souvenir: number;
            /** Format: double */
            transportation: number;
            /** Format: double */
            waste: number;
        };
        Scope3Review: {
            attendee: components["schemas"]["ReviewCheck"];
            overnight: components["schemas"]["ReviewCheck"];
            souvenir: components["schemas"]["ReviewCheck"];
            waste: components["schemas"]["ReviewCheck"];
        };
        Scope3WithTransportations: {
            attendee: components["schemas"]["Attendee"][] | null;
            overnight: components["schemas"]["Overnight"][] | null;
            souvenir: components["schemas"]["Souvenir"][] | null;
            transportations?: components["schemas"]["Transportation"][] | null;
            waste: components["schemas"]["Waste"][] | null;
        };
        Souvenir: {
            type: string;
            unit: string;
            /** Format: int64 */
            value: number;
        };
        Transportation: {
            id: string;
            origin: components["schemas"]["Origin"];
            project_id: string;
            type: string;
        };
        UpdateProjectStatusRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateProjectStatusRequestBody.json
             */
            readonly $schema?: string;
            status: string;
        };
        Waste: {
            type: string;
            unit: string;
            /** Format: double */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-dashboard": {
        parameters: {
            query?: {
                /** @description Academic year for totals and heatmap. Defaults to current_year if omitted or 0. */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDashboardResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-owners-me": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOwnerResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-owners-validate": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-projects": {
        parameters: {
            query: {
                /** @description Number of items to skip, used for pagination */
                offset?: number;
                /** @description Maximum number of items to return */
                limit: number;
                /** @description Search term applied to 'title' or 'custom_id' */
                search?: string;
                /** @description Sort field (custom_id,title,status,org,created_at,updated_at,updated_by), prefix with '-' for descending */
                sort?: string;
                /**
                 * @description Comma-separated statuses to filter on
                 * @example pending,draft,fixing
                 */
                status?: string;
            };
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-projects": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description CarbonDetail encoded as JSON */
                    carbon_detail?: string;
                    custom_id?: string;
                    org?: string;
                    org_detail?: string;
                    owner_fullname?: string;
                    owner_line_id?: string;
                    owner_major?: string;
                    owner_nickname?: string;
                    owner_phone_number?: string;
                    owner_student_id?: string;
                    status?: string;
                    title?: string;
                    /**
                     * Format: binary
                     * @description This is optional
                     */
                    transportations_csv_file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateProjectResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-projects-id": {
        parameters: {
            query?: {
                include_transportations?: boolean;
                include_review?: boolean;
            };
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProjectResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-projects-id": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "patch-projects-id": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description CarbonDetail encoded as JSON */
                    carbon_detail?: string;
                    custom_id?: string;
                    org?: string;
                    org_detail?: string;
                    owner_fullname?: string;
                    owner_line_id?: string;
                    owner_major?: string;
                    owner_nickname?: string;
                    owner_phone_number?: string;
                    owner_student_id?: string;
                    title?: string;
                    /**
                     * Format: binary
                     * @description This is optional
                     */
                    transportations_csv_file?: string;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-projects-id-calculate": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCarbonEmissionResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-projects-id-certificate": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-projects-id-review": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewUpsertInput"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-projects-id-status": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectStatusRequestBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-projects-id-transportations": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-projects-emissionfactors": {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetEmissionFactorResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
